apiVersion: v1
kind: Namespace
metadata:
  name: apilaf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apilaf
  name: apilaf
  namespace: apilaf
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apilaf
  template:
    metadata:
      labels:
        app: apilaf
    spec:
      containers:
      - image: oaworkshop.azurecr.io/oalaf:3000
        env:
        - name: WORKFLOW_URI
          value: "here you workflow (Power Automate or Logic Apps) URL"
        name: apilaf
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "1Mi"
            cpu: "100m"
          limits:
            memory: "2Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
    name: apilaf
    namespace: apilaf
    labels:
        app: apilaf
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: apilaf
